language: java
jdk: oraclejdk8
script:
- "./gradlew build"
deploy:
  provider: cloudfoundry
  api: api.run.pivotal.io
  username: connor.shaughnessy@gmail.com
  password:
    secure: DfajwQ3KYJIao2qBcIf6Ktmj+bTEfiMyWf3BgMkWJGzIDcZICEC8x1RdrhC//LLG74tUBTZhoUjoGbSEK0mcH4j6olNlr8RUZlxAVlaKnmVOfO03yIGnKN6IC7BUulM67rc3ZDIFfMFVcvldarbyhwc0GOg0c3qtb9NCxLu0GkzkTHtEFvpmDm/aHAyBBMTP6AGdqqb/GgU5fTPJrwF/A2IOQZRzSk5oaH6riTK2sJSpoZYB2NAeAooSHPnmSKJht/f/wCp5oTwdKlrGYlUAP7GAp/2tOmCX709zP/B+p6XqxplrBMS7Yx210nj7pcXANna6voZ93vDZZFhk9MiTfE6jxZtexwM0r5yPBZn4DaLSeFj+qpICKKjw1uunbBOpg1DHxYIYvo06N8VvnP0S92KGMIh5RkpxFXdaVabHuwwnlPlKv9qir8M9gr8v2NqTmg8/gxz5oQOMZPguL6mG+4OS5iEmjAQLPolRxuYg55noL0I+VJqEI/L3NPiQUPwEu5ep57I+wiO3/w8uQxjyc9ugaASYIrs3U+ht+51Jf5hkIdvbniFksB9GTmoGwfIt5XOwqXmuRYVMZj9xkLUoxNVvla7zvCNiaZTMmozQXKlsSDn/uHON1dmuO8HuQMdrUCMoDeeXMObHokIBxmv4d59gclF4gCXLvgb2wIZU0DY=
  organization: upwise
  space: prod
  on:
    repo: sapphon/upwise
    branch: deploy
